name: "Testing WorkFlow"

on:
  push:
    branches-ignore:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ğŸ””
        uses: actions/checkout@v3

      - name: Setup Node â˜Š
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies âš™ï¸
        run: npm ci

      - name: Run type checking
        run: npm run tsc:check

      - name: Checking Code Formatting ğŸ©ğŸ‘”ğŸ‘
        run: npm run format:check

      - name: Checking Code Linting ğŸ˜‡ğŸ•Šï¸
        run: npm run lint:check

      - name: Runs Tests ğŸ§ª
        run: npm run test

      - name: Checking Project Build ğŸ”¨ğŸ‘·ğŸ¾â€â™€ï¸â›ï¸
        run: npm run build

      - name: Upload coverage reports to Codecov ğŸ“ˆ
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
